<?xml version="1.0"?>
<!-- =================================================================================== -->
<!-- |    One One finger with two links. The top finger tip is rectangle			   | -->
<!-- =================================================================================== -->
<robot name="3FingersRobot" xmlns:xacro="http://www.ros.org/wiki.xacro">
	<xacro:property name="l1" value="0.15"/>
	<xacro:property name="l2" value="0.1"/>
	<xacro:property name="finger_width" value="0.02"/>
	<xacro:property name="finger_thick" value="0.005"/>
	<xacro:property name="m1" value="0.5"/>
	<xacro:property name="m2" value="0.5"/>

	<material name="white">
		<color rgba="0.8 0.8 0.8 1"/>
	</material>

	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<material name="green">
		<color rgba="0 0.8 0 1"/>
	</material>

	<link name="base_link">
		<visual>
			<geometry>
				<box size="0.1 0.1 0.05"/>
			</geometry>
			<material name="white" />
		</visual>
		<collision>
			<geometry>
				<box size="0.1 0.1 0.05"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="1"/>
			<inertia ixx="1e-3" iyy="1e-3" izz="1e-3" ixy="0" ixz="0" iyz="0"/>
			<origin xyz="0 0 0" />
		</inertial>
	</link>

	<link name="root_finger">
		<visual>
			<geometry>
				<box size="${l1} ${finger_width} ${finger_thick}"/>
			</geometry>
			<origin xyz="${l1/2.0} 0 0"/>
		</visual>
		<collision>
			<geometry>
				<box size="${l1} ${finger_width} ${finger_thick}"/>
			</geometry>
			<origin xyz="${l1/2.0} 0 0"/>
		</collision>
		<inertial>
			<origin xyz="${l1/2.0} 0 0" />
			<mass value="${m1}" />
			<inertia
				ixx="${1/12.0*m1*(finger_thick*finger_thick+finger_width*finger_width)}"
				iyy="${1/12.0*m1*(l1*l1+finger_thick*finger_thick)}"
				izz="${1/12.0*m1*(l1*l1+finger_width*finger_width)}"
				ixy="0" iyz="0" ixz="0"/>
		</inertial>
	</link>

	<link name="top_finger">
		<visual>
			<geometry>
				<box size="${l2} ${finger_width} ${finger_thick}"/>
			</geometry>
			<origin xyz="${l2/2.0} 0 0"/>
		</visual>
		<collision>
			<geometry>
				<box size="${l2} ${finger_width} ${finger_thick}"/>
			</geometry>
			<origin xyz="${l2/2.0} 0 0"/>
		</collision>
		<inertial>
			<origin xyz="${l2/2.0} 0 0" />
			<mass value="${m2}" />
			<inertia
				ixx="${1/12.0*m2*(finger_thick*finger_thick+finger_width*finger_width)}"
				iyy="${1/12.0*m2*(l2*l2+finger_thick*finger_thick)}"
				izz="${1/12.0*m2*(l2*l2+finger_width*finger_width)}"
				ixy="0" iyz="0" ixz="0"/>
		</inertial>
	</link>

	<joint name="base_to_root_joint" type="revolute">
		<parent link="base_link"/>
		<child link="root_finger" />
		<origin xyz="0 0 ${0.05+finger_thick/2.0}"/>
		<axis xyz="0 0 1"/>
		<limit effort="1000.0" lower="-3.14" upper="3.14"  velocity="0.5"/>
		<dynamics damping="0" friction="0"/>
	</joint>

	<joint name="root_to_top_joint" type="revolute">
		<parent link="root_finger"/>
		<child link="top_finger" />
		<origin xyz="${l1} 0 0"/>
		<axis xyz="0 0 1"/>
		<limit effort="1000.0" lower="-3.14" upper="3.14"  velocity="0.5"/>
		<dynamics damping="0" friction="0"/>
	</joint>
</robot>
