<?xml version="1.0"?>
<robot name="3FingersRobot" xmlns:xacro="http://www.ros.org/wiki.xacro">
	<xacro:property name="base_link_w" value="0.6"/>
	<xacro:property name="base_link_h" value="0.4"/>
	<xacro:property name="base_link_t" value="0.02"/>

	<xacro:property name="f1_x" value="0"/>
	<xacro:property name="f1_y" value="0.2"/>
	<xacro:property name="f2_x" value="-0.1"/>
	<xacro:property name="f2_y" value="-0.2"/>
	<xacro:property name="f3_x" value="0.1"/>
	<xacro:property name="f3_y" value="-0.2"/>

	<xacro:property name="l1" value="0.15"/>
	<xacro:property name="l2" value="0.1"/>
	<xacro:property name="l_w" value="0.02"/>
	<xacro:property name="l_t" value="0.005"/>
	<xacro:property name="m1" value="0.5"/>
	<xacro:property name="m2" value="0.5"/>

	<material name="white">
		<color rgba="0.8 0.8 0.8 1"/>
	</material>

	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<material name="green">
		<color rgba="0 0.8 0 1"/>
	</material>

	<xacro:macro name="default_inertial" params="mass">
		<inertial>
			<mass value="${mass}"/>
			<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
		</inertial>
	</xacro:macro>

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_link_w} ${base_link_h} ${base_link_t}"/>
			</geometry>
			<origin xyz="0 0 0"/>
			<material name="white" />
		</visual>
		<collision>
			<geometry>
				<box size="${base_link_w} ${base_link_h} ${base_link_t}"/>
			</geometry>
			<origin xyz="0 0 0"/>
		</collision>
		<xacro:default_inertial mass="0"/>
	</link>

	<xacro:macro name="finger" params="prefix x y theta">
        <link name="${prefix}_root_finger">
            <visual>
				<geometry>
                    <cylinder radius="${l_w/2.0*1.1}" length="0.02"/>
                </geometry>
                <origin xyz="0 0 0"/>
			</visual>
            <visual>
				<geometry>
                    <box size="${l1} ${l_w} ${l_t}"/>
                </geometry>
                <origin xyz="${l1/2.0} 0 0"/>
			</visual>
			<collision>
				<geometry>
                    <box size="${l1} ${l_w} ${l_t}"/>
                </geometry>
                <origin xyz="${l1/2.0} 0 0"/>
			</collision>
		    <inertial>
                <origin xyz="${l1/2.0} 0 0" />
                <mass value="${m1}" />
                <inertia
						ixx="${1/12.0*m1*(l_w*l_w+l_t*l_t)}"
						iyy="${1/12.0*m1*(l1*l1+l_t*l_t)}"
						izz="${1/12.0*m1*(l1*l1+l_w*l_w)}"
                    	ixy="0" iyz="0" ixz="0"/>
            </inertial>
		</link>

		<joint name="${prefix}_base_to_root" type="revolute">
			<parent link="base_link"/>
			<child link="${prefix}_root_finger" />
            <origin xyz="${x} ${y} 0.02" rpy="0 0 ${theta}"/>
            <axis xyz="0 0 1"/>
	        <limit effort="10000.0" lower="-3.14" upper="3.14"  velocity="5"/>
	        <dynamics damping="0" friction="0"/>
		</joint>
    
        <link name="${prefix}_top_finger">
            <visual>
				<geometry>
					<box size="${l2} ${l_w} ${l_t}"/>
				</geometry>
                <origin xyz="${l2/2.0} 0 0"/>
                <material name="green"/>
			</visual>
			<collision>
				<geometry>
					<box size="${l2} ${l_w} ${l_t}"/>
				</geometry>
                <origin xyz="${l2/2.0} 0 0"/>
			</collision>
            <inertial>
                <origin xyz="${l2/2.0} 0 0" />
                <mass value="${m2}" />
                <inertia
						ixx="${1/12.0*m2*(l_w*l_w+l_w*l_w)}"
						iyy="${1/12.0*m2*(l2*l2+l_w*l_w)}"
						izz="${1/12.0*m2*(l2*l2+l_w*l_w)}"
                    	ixy="0" iyz="0" ixz="0"/>
            </inertial>
		</link>

        <joint name="${prefix}_root_to_top" type="revolute">
            <parent link="${prefix}_root_finger"/>
			<child link="${prefix}_top_finger" />
            <origin xyz="${l1} 0 0"/>
            <axis xyz="0 0 1"/>
	        <limit effort="10000.0" lower="-3.14" upper="3.14"  velocity="5"/>
	        <dynamics damping="0" friction="0"/>
		</joint>
       	</xacro:macro>

	<xacro:finger prefix="1" x="${f1_x}" y="${f1_y}" theta="3.1415/2.0"/>
	<xacro:finger prefix="2" x="${f2_x}" y="${f2_y}" theta="0"/>
	<xacro:finger prefix="3" x="${f3_x}" y="${f3_y}" theta="0"/>
</robot>
